### ISSUE TITLE
RN2483 ICSP Protection

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/watertemp-hardware#7]
> During High Voltage In-Circuit Serial Programming
> mode, the RESET pin is driven with high-voltage (9V),
> therefore protection may be necessary for sensitive
> devices

Do we need something like that?

**Comment by dbrgn** [comment]
@rnestler ping :)

**Comment by rnestler** [comment]
Maybe we could just add a solder bridge?

**Comment by rnestler** [comment]
> The  normal  firmware  upgrade  method  is  through  the
internal  bootloader  of  the  module  via  the  UART. 
> http://ww1.microchip.com/downloads/en/DeviceDoc/50002346C.pdf

So this would be highly unlikely that we ever need it. So a solder bridge between RN_RST and the pull-up resistor would definitely be enough.

**Comment by dbrgn** [comment]
A solder bridge is a bit annoying if we have to add it for every board.

If we ever need to use ICSP, we can simply desolder the pull-up, that'll result in the same thing.
