### ISSUE TITLE
Programming the RN2483

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/watertemp-hardware#8]
Seems that it would be possible to program the RN2483 directly?

https://www.thethingsnetwork.org/forum/t/microchip-released-rn2483-library-code/4439

Would that suffice for our use case? It wouldn't be mbed compatible anymore though.

**Comment by rnestler** [comment]
> The documentation states loading your own firmware on the module invalidates the certification.

From the linked forum. Is this a problem for us?

**Comment by dbrgn** [comment]
Nope, as long as we don't sell our sensors as LoRaWAN certified devices :)

**Comment by dbrgn** [comment]
The question is rather whether we have some significant limitations that we don't want to accept. With an external MCU we're probably more flexible.

**Comment by dbrgn** [comment]
@rnestler we should probably stick to the external MCU, right?

**Comment by rnestler** [comment]
For the moment yes.
